[package]
name = "rustagram"
version = "0.1.0"
authors = ["Htet Aung Shine <h@shine.rocks>"]

[dependencies]
image = "*"
rayon = "1.0"
clap = "*"

[[bin]]
name = "rustagram"
path = "src/main.rs"

[[bin]]
name = "producer"
path = "src/producer.rs"